[package]
name = "ex32"
version = "0.1.0"
authors = ["Your Name <276477233@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
